"""SQLite index: gyors lekérdezések a könyvtárra, ismételhető szinkronnal."""

from .album_collage import (
    COLLAGE_PROJECT_NAME,
    albums_with_collage,
    folder_has_collage,
)
from .albums import AlbumRecord, album_photos, albums_in_index
from .colors import (
    backfill_colors,
    color_index_progress,
    compute_photo_color,
    load_color_tokens,
    paths_with_color,
    save_colors,
)
from .database import open_index
from .face_groups import face_groups, group_unnamed_faces
from .faces_detected import (
    PendingEmbeddingFace,
    UnnamedFace,
    clear_faces,
    detected_face_count,
    face_embedding,
    faces_missing_embedding,
    ignored_faces,
    named_centroids,
    mark_faces_ignored,
    mark_faces_named,
    replace_faces,
    reset_all_faces,
    store_embedding,
    unnamed_album_photos,
    set_suggested_name,
    suggested_faces,
    unignore_faces,
    unnamed_faces,
)
from .hashes import load_dhashes, save_dhashes
from .queries import (
    PhotoRecord,
    SearchSuggestion,
    all_photos,
    geotagged_photos,
    photo_by_id,
    photos_in_folder,
    photos_under_folder,
    search_photos,
    search_suggestions,
    starred_photos,
    video_photos,
)
from .people import (
    PersonRecord,
    people_in_index,
    people_with,
    person_photos,
)
from .project_folders import ProjectFolder, project_folders
from .relocate import (
    RelocationCancelled,
    RelocationError,
    RelocationProgress,
    RelocationResult,
    relocate_data_root,
)
from .schema import SCHEMA_VERSION
from .sync import (
    add_removed_folder,
    clear_removed_folders_under,
    folder_looks_offline,
    folder_paths_under,
    folder_scan_stamps,
    move_folder_tree,
    removed_folder_paths,
    prune_foreign_folders,
    remove_root,
    sync_folder,
    sync_tree,
    update_photo_fields,
    watched_root_missing,
)

__all__ = [
    "COLLAGE_PROJECT_NAME",
    "SCHEMA_VERSION",
    "AlbumRecord",
    "PendingEmbeddingFace",
    "UnnamedFace",
    "PersonRecord",
    "PhotoRecord",
    "ProjectFolder",
    "RelocationCancelled",
    "RelocationError",
    "RelocationProgress",
    "RelocationResult",
    "album_photos",
    "albums_in_index",
    "albums_with_collage",
    "all_photos",
    "backfill_colors",
    "color_index_progress",
    "clear_faces",
    "compute_photo_color",
    "detected_face_count",
    "face_embedding",
    "face_groups",
    "faces_missing_embedding",
    "folder_scan_stamps",
    "geotagged_photos",
    "video_photos",
    "group_unnamed_faces",
    "load_color_tokens",
    "load_dhashes",
    "ignored_faces",
    "named_centroids",
    "mark_faces_ignored",
    "mark_faces_named",
    "open_index",
    "paths_with_color",
    "people_in_index",
    "people_with",
    "person_photos",
    "photo_by_id",
    "unnamed_album_photos",
    "photos_in_folder",
    "photos_under_folder",
    "folder_has_collage",
    "project_folders",
    "prune_foreign_folders",
    "relocate_data_root",
    "add_removed_folder",
    "clear_removed_folders_under",
    "remove_root",
    "folder_paths_under",
    "move_folder_tree",
    "removed_folder_paths",
    "replace_faces",
    "reset_all_faces",
    "save_colors",
    "save_dhashes",
    "SearchSuggestion",
    "search_photos",
    "search_suggestions",
    "starred_photos",
    "store_embedding",
    "sync_folder",
    "sync_tree",
    "set_suggested_name",
    "suggested_faces",
    "unignore_faces",
    "unnamed_faces",
    "update_photo_fields",
    "folder_looks_offline",
    "watched_root_missing",
]
